# Generated by Django 4.1.7 on 2023-09-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
